spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 8462519573
  application:
    name: microservice-flight
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    vault:
      host: vault-custom
      port: 8200
      scheme: http
      authentication: TOKEN
      kv:
        backend: kv
        default-context: database
        application-name: database
        enabled: true
  config:
    import: vault://
  flyway:
    locations: classpath:/db/migration

server:
  port: 9003

eureka:
  instance:
    instance-id: microservice-flight
  client:
    fetch-registry: true