package ar.com.l_airline.domain;

public enum AirlineName {
    TITAN_AIR,
    CLOUD_HAWK,
    SILVER_FALCON,
    ARCTIC_EAGLE,
    EMERALD_JET,
    STARLIGHT_AIR,
    RENGOKU,
    INFINITY_SKY,
    CRIMSON_CRANE,
    BLUE_WHALE_AIR,
    PHOENIX_FLYERS,
    ZENITH_FLYERS,
    NOVA_AIRWAYS,
    ROYAL_PHOENIX,
    GOLDEN_HORIZON,
    SKY_WINGS,
    AURORA_BIRD,
    LUCENT_WINGS,
    ECLIPSE_JET,
    SAPPHIRE_SKY
}
